temp_file=open("temp.txt","w")
print("First line",file=temp_file)
print("Second line",file=temp_file)
print("Third line",file=temp_file)
print("Fourth line",file=temp_file)
temp_file.close()
print("---")
temp_file=open("temp.txt","r")
file=temp_file.read()
print(file)
temp_file.close()
print("---")
temp_file=open("temp.txt","r")
file=temp_file.readline()
print(file)
temp_file.close()
print("---")
temp_file=open("temp.txt","r")
file=temp_file.readlines()
print(file)
temp_file.close()
word_list=['First line\n', 'Second line\n', 'Third line\n', 'Fourth line\n']
out_file=open("out.txt","w")
for word in word_list:
    out_file.write()